forcedotcom/SalesforceMobileSDK-Package

- shared/commandLineUtils.js
- shared/configHelper.js
- shared/createHelper.js
- shared/utils.js
- test/test_force.js
Instead of create and createWithConfig, we now have create and createWithTemplate.
* create expects an apptype (along with appname, packagename, organization, and optionally outputdir)
* createWithTemplate instead expects a templaterepourl (also with appname, packagename, organization, and optionally outputdir)
That way it should be close to what it was before for users that do not care about templates.
That was made possible by having templates know their own app type (see https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/7)
Finally the pluginrepourl (to use another plugin repo) and templatepath (to allow a template repo to host multiple templates) are now "hidden" arguments (they are not shown by usage and are never prompted to the user - they will however be used if …
> Better forceios/forcedroid actions

- fastlane/Fastfile
`Fastlane` was using the hard coded `master` branch for `SmartSyncExplorerReactNative` whereas everything else was using `dev` branch from `$branch` variable. This was causing test failures (false positives).
> Fix lane file to use correct branch

- shared/configHelper.js
* The longDescription values are used only in the reference doc. 
* The description values are used only on the command line. 
* The help values are used in both places (and, on the command line, the -h | --help output also includes some info in addition to the help property's value). 
So, for commands, description and longDescription should basically contain the same information, and should not duplicate what's in help (which is the appropriate place for usage notes and examples). 
For parameters, it's ok to put extra info that you want to include in the reference doc in longDescription but not in description, but just keep in mind that that info will be visible only in the reference doc.
> Exposing command's description in longDescription field

- sfdx/index.js
- shared/configHelper.js
- shared/constants.js
Added longDescriptions to the commands and doctored the code to read them. The longDescriptions added are exactly the same as the descriptions, but they are styled for the upcoming Reference.
> Adding longDescriptions back in for inclusion in Reference

- test/test_force.js
To test published forcexxx for all app types/platform, do:
```shell
./test/test_force.js --os=ios,android --apptype=native,native_kotlin,native_swift,hybrid_local,hybrid_remote,react_native --test-production
```
To test published sfdx-mobilesdk-plugin for all app types/platform, do:
```shell
./test/test_force.js --os=ios,android --apptype=native,native_kotlin,native_swift,hybrid_local,hybrid_remote,react_native --use-sfdx --test-production
```
> New flag --test-production to test published forcexxx and sfdx plugin

- hybrid/package.json
- react/package.json
This PR bumps up only the package version because that's all we need to publish a new package. There are no code changes elsewhere, so the tags remain the same (`v6.0.0`).
> Removing Mac OS Requirement for forcehybrid and forcereact

- shared/constants.js
Currently the min version required for the cordova cli is 7.0.0.
If you use that version, then you must use node 6. It throws an error with node 8.
However if you use cordova cli 8.0.0, then it works with node 6 and node 8.
=> In Mobile SDK 6.2, we should require cordova cli 8 so that they can use any versions of node they want.
> Fixes node 8 issue

- .gitignore
- android/README.md
- hybrid/README.md
- ios/README.md
- react/README.md
- sfdx/README.md
- sfdx/generate_readme.sh
- sfdx/index.js
- shared/configHelper.js
- shared/constants.js
- shared/createHelper.js
- shared/templateHelper.js
It returns the available and applicable templates for that cli.
It fetches the list of templates from the templates.json (see https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/121) file at the root of the template repo specified in constants.js (it will be https://github.com/forcedotcom/SalesforceMobileSDK-Template#v6.2.0 once 6.2 ships).
```shell
$ forceios listtemplates
Available templates:
1) Basic Swift application
forceios createwithtemplate --templaterepouri=https://github.com/wmathurin/SalesforceMobileSDK-Templates/iOSNativeSwiftTemplate#dev
2) Basic Objective-C application
forceios createwithtemplate --templaterepouri=https://github.com/wmathurin/SalesforceMobileSDK-Templates/iOSNativeTemplate#dev
3) Sample Swift Identity Provider application
forceios …
```
> New action for force clis: listtemplates

- shared/constants.js
- shared/createHelper.js
- shared/utils.js
Adding max version supported (optional) in constants.js
Adding max version supported (1.4) for cocoapods
Adding min/max versions supported (6.9-8.11) for node
> Max version check for 3rd party tools

- shared/templateHelper.js
- test/test_force.js
Usage is now:
```shell
test_force.js
--os=os1,os2,etc  OR --cli=cli1,cli2,etc
(when using --os) --apptype=appType1,appType2,etc OR --templaterepouri=TEMPLATE_REPO_URI
[--use-sfdx]
[--test-production]
[--pluginrepouri=PLUGIN_REPO_URI (Defaults to uri in shared/constants.js)]
[--sdkbranch=SDK_BRANCH (Defaults to dev)]
Where:
- osX is : ios or android
- cliX is : forceios or forcedroid or forcehybrid or forcereact
- appTypeX is: native, native_swift, native_kotlin, react_native, hybrid_local or hybrid_remote
- templaterepouri is a template repo uri e.g. https://github.com/forcedotcom/SalesforceMobileSDK-Templates/SmartSyncExplorerReactNative#dev
```
For example, to generate/compile all templates available to forcedroid (including basic templates), do:
```shell
./test/test_force.js …
```
> New param for test_force to generate/compile apps based on all available templates

- shared/constants.js
Node lts is [now](https://medium.com/@nodejs/october-brings-node-js-10-x-to-lts-and-node-js-11-to-current-ae19f8f12b51) 10.x and current is 11.x.
I tested 11.1 and didn't run into any issues.
> Max version of node supported moved to 11.1

- shared/constants.js
Two reasons
1) our use of node is very basic (we no longer pull dependencies with node instead we use git) so unlikely to break
2) there are new versions of node all the time, it's very annoying to get the `Please downgrade your version of node.` message when running one of the force tool.
> Dropping max version check for node

- shared/utils.js
Now it will work with new lines in the version string like Cordova's (when run for the first time).
> Handling version number that starts with other characters

- shared/createHelper.js
Using legacy builds for hybrid iOS apps. Using the new build system fails to build hybrid iOS apps leads to intermittent failures. 
We create a WorkspaceSettings.xcsettings plist in the xcshareddata location for the project.
> Sets the BuildSystemType to Original(Legacy) for hybrid iOS apps

- android/package.json
- hybrid/package.json
- ios/package.json
- react/package.json
- sfdx/package.json
- shared/constants.js
- test/test_force.js
Got rid rid of --test-production and --sdkbranch:
* sdk branch is inferred from pluginrepouri
* local updated clone of plugin repo is only used if pluginrepouri does not point to tag
=> to test production, simply run ./test_force.js in master - it will still create npm packages but they should be the ones about to or already published to production
> Fixing test_force.js to test CLIs about to or already published to production

- .circleci/config.yml
- test/test_force.js
When provided, we don't run ./tools/update.sh on the clone of the plugin repo when testing forcehybrid
Using that new option in CI to speed testing up.
In the past, cordova plugin repo had binaries, and we only updated them on release day.
Now it only hold sources, so as long as the sources are up to date, there is no point running ./tools/update.sh when testing hybrid.
> test_force.js has a new option --no-plugin-update

- shared/constants.js
- test/test_force.js
All iOS bundles now use dash (except hybrid because cordova errors) and all Android packages use underscores.  Templates are parsed out by word and use dash or underscore based on os.  The prefixed "App_" and postfixed "_ios/_android/_dev" have been removed from app name and bundle/package strings.
> Cleanup test_force bundle/package naming.

- release/setup_test_branches.js
- test/test_force.js
Also with the last PR, it was no longer possible to do `test_force.js --cli=forcehybrid`, because the generated app for iOS and Android would be named the same, and so the second one would throw an error
> Simplifying generated app's name and package generation

- android/README.md
- hybrid/README.md
- ios/README.md
- react/README.md
- sfdx/README.md
- shared/configHelper.js
- shared/constants.js
- shared/createHelper.js
- shared/templateHelper.js
- test/test_force.js
Also output of list templates also show just the name e.g.
```shell
$ forceios listtemplates
Available templates:
1) Basic Swift application
forceios createwithtemplate --templaterepouri=iOSNativeSwiftTemplate
```
Instead of
```shell
$ forceios listtemplates
Available templates:
1) Basic Swift application
forceios createwithtemplate --templaterepouri=https://github.com/forcedotcom/SalesforceMobileSDK-Templates/iOSNativeSwiftTemplate#v7.3.0
```
> When creating from Mobile SDK template, name can be passed instead of full URL

- shared/constants.js
Before it was 1.7.2-1.9.
Successfully generated and compiled iOS apps with test_force.js
> Changing supported cocoapod version to 1.8-1.9.1 

- README.md
- sfdx/README.md
- shared/constants.js
- shared/createHelper.js
- shared/utils.js
**The generated application for the new apptype contains a server project that uses Lightning Web Components with Mobile SDK.**
This PR for the new templates is: https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/272
The screenshot below shows:
* the output of running forcehybrid with the new apptype. Note the new "next steps" instructions for the server project,
* what the basic lwc template app looks like.
> New apptype for forcehybrid: hybrid_lwc

- shared/constants.js
It's unlikely cocoapod 2 will release any time soon. I don't expect 1.9.x to break anything.
> Dropping max version for cocoapod

- test/test_force.js
For a while now, we have allowed a template name instead of a full URI.
As a result, some of the generated messages in test_force.js were no longer correct (they were trying to parse out the branch from the name, finding none, and concluding it was coming from master).
> Fixing some of the log lines coming from test_force.js

- sfdx/package.json
- shared/constants.js
- test/test_force.js
It is also the default when using forcereact.
- Change to usage
```shell
$ forcereact
forcereact: Tool for building a React Native mobile application using Salesforce Mobile SDK
Usage:
forcereact create
--platform=comma-separated list of platforms (ios, android)
[--apptype=application type (react_native_typescript or react_native, leave empty for react_native_typescript)]
--appname=application name
--packagename=app package identifier (e.g. com.mycompany.myapp)
--organization=organization name (your company's/organization's name)
[--outputdir=output directory (leave empty for current directory)]
(...)
```
- Change when running forcereact create
```
$ forcereact create
Enter the target platform(s) separated by commas (ios, android): ios
Enter your application type (react_native_typescript …
```
> New apptype for forcereact: react_native_typescript

- release/package.json
To avoid circular dependencies warning with newer version of node
> Upgrading to shelljs 0.8.4

- release/release.js
- shared/constants.js
NB: no need to run setversions.sh on the various repos to set them to 9.1.1 (they currently are set to 9.2.0), the release script takes care of it.
I ran a full "dry" run of the release, including running test_force.js and found not issues. 
See branches dev2 and master2 on the various repos in my forks.
> Getting ready for 9.1.1

- release/common.js
- release/package.json
- release/release.js
- release/setup_test_branches.js
A patch release is one where the changes are already in master and for which no dev to master merge should take place.
I'm currently testing by make "dry runs" of:
* a 9.2.1 patch release
* a 10.0.0 regular release
Issues I was running into had to do with the "dry run" setup which consists in having master2 dev2 branches setup everywhere and correctly referenced in submodules etc. When done improperly, it can lead to conflicts during merges (especially when submodules are involved).
> Release.js (and setup_test_branches.js) can now be used for patch releases

- .circleci/config.yml
- android/package.json
- hybrid/package.json
- ios/package.json
- react/package.json
- release/package.json
- sfdx/package.json
- shared/createHelper.js
- Add Xcode 14/iOS 16 beta runs.
- Convert triggers from deprecated Scheduled Workflows to Scheduled Pipelines, specified in "Triggers" tab of project settings on CircleCi website. This change makes triggering tests manually though the GUI possible (and easy) against any branch.
> Modernize CircleCI config and add iOS beta runs.

- .circleci/config.yml
- shared/constants.js
WIP
- Android not compiling (because of gradle changes)
- Pointing to wmathurin/SalesforceMobileSDK-CordovaPlugin#dev until everything passes and this [PR](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/624) is merged
> Using cordova-android 12.0.1 and cordova-ios 7.0.1

- release/setup_test_branches.js
`setup_test_branches.js` takes care of creating master2, dev2 branches that mirror master, dev in all the repos of the forked org.
It also makes sure the submodules and package.json point to the forked org (and not forcedotcom).
Most recent template's package.json were not updated causing test_force.js to fail during a dry run.
> Most recent templates were not properly setup during dry run

- .circleci/config.yml
- shared/constants.js
- shared/createHelper.js
- test/test_force.js
It's also exposed as a new optional argument for `test_force.js`.
Use SDK dependencies override if you need to generate/build a template pointing to some fork/branch of Mobile SDK. To do that before, you would have to change the package.json of the template in your fork, check it in and then run test_force.js with templaterepouri pointing to your fork.
To build the template using the forked Salesforce Mobile SDK iOS repo pass the following:
```
--sdkdependencies={\"SalesforceMobileSDK-iOS\":\"https://github.com/somefork/SalesforceMobileSDK-iOS#somebranch\"}
```
There is also a new flag spm-update for `test_force.js`. When provided the SPM repo is cloned and build locally and then the CLIs is invoked with SalesforceMobileSDK-iOS-SPM pointing to the local directory (using the sdk …
> Ability to override sdk dependencies in forceios/forcedroid etc and test_force.js / also new test_force.js flag to do SPM update (locally)

- test/test_force.js
Otherwise MobileSyncExplorerSwift was not compiling because a catalyst destination was used but. RecentContactsExtension does not compile there:
```
!FAILURE! COMPILING native_swift app for ios based on template MobileSyncExplorerSwift (dev)
Command failed: xcodebuild -workspace /Users/distiller/SalesforceMobileSDK-Package/tmp20241007T230359.281/iosmobilesyncexplorerswift/iosmobilesyncexplorerswift.xcworkspace -scheme iosmobilesyncexplorerswift clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Mac Catalyst, id:0000FE00-8D8861F646F3907A, name:My Mac }
...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ …
```
> Not letting xcodebuild pick the destination randomly
