android/forcedroid.js
ios/forceios.js
shared/configHelper.js
shared/constants.js
shared/createHelper.js
shared/pack.js
shared/utils.js
test/test_force.js

prepare for hybrid app was run too soon
also test_force.js not building libs for cordova plugin if local path is provided

Misc fixes (hybrid generation)

---

README.md
install.js
pack/pack.js
shared/configHelper.js
shared/createHelper.js
shared/utils.js
test/test_force.js

* os argument for test_force.js is no longer case sensitive
* if output directory specified for forceios/droid already exist, the user is re-prompted right away
* pack.js moved to pack folder
* added readme and install.js script that should be run before running ios/forceios.js, android/forcedroid.js, test/test_force.js or pack/pack.js

Implementing recommendations

---

shared/utils.js

Trivial fix for quoting directory paths.

Fix: Related to spaces in folder names

---

shared/constants.js

See [here](https://github.com/forcedotcom/react-native/blob/sdk/React.podspec#L42)

React native pod spec requires cocoapod 1.2

---

test/test_force.js

NB: That change is needed also in dev

Fixed regression - was always generating apps from default templates

---

android/README.md
hybrid/README.md
ios/README.md
react/README.md
sfdx/README.md
sfdx/generate_readme.sh
sfdx/index.js
shared/configHelper.js
shared/constants.js
test/test_force.js

* createwithtemplate instead of createWithTemplate
* -k for packagename (-p is already used for platform)
NB: forceios/forcedroid will still accept createWithTemplate -- they don't care about the case of the command typed

Feedback from sfdx doc review

---

shared/constants.js
shared/createHelper.js
shared/utils.js

Getting rid of templatepath parameter (NB: it was never made public / documented).
Instead we compute it from the templaterepouri.

Inferring template path from templaterepouri parameter

---

shared/constants.js

Also (re)fixed the capitalization on description text.

Added longDescription tags where appropriate.

---

README.md

Not worth moving the tag.  Just doing it now so it doesn't get forgotten for 6.1.

Add forcereact to first line of readme.

---

.circleci/config.yml

Only build on pull request right now.  We can expand this to actually running the app and logging in for a nightly run at some point in the future.

Build Apps in CirlceCI

---

.circleci/config.yml

- Build all iOS templates for forceios and sfdx
- Temporarily set to Mon/Wed/Fri to better test iOS while we have the trial.

Build iOS Apps

---

shared/constants.js

Added a sentence to the listtemplates help content.

Added a sentence to the listtemplates help content.

---

android/README.md
hybrid/README.md
ios/README.md
sfdx/README.md
shared/constants.js
shared/createHelper.js

It default to native_swift for forceios (and native for forcedroid, hybrid_local for forcehybrid).
Updated help texts and README's accordingly.

Apptype is optional

---

.circleci/config.yml

Also updated xcode & android api version + associated dependencies.

Fix Uncaught Failures

---

ios/package.json
shared/constants.js

7.0.0.preview is not a valid version name for npm
also version updated in package.json of forceios

Preview version will be 7.0.0-preview (instead of 7.0.0.preview)

---

.circleci/config.yml
shared/constants.js

We no longer need to downgrade cocoapod during CI

FMDB fixed the issue that was preventing us from using cocoapod 1.5

---

test/test_force.js

Ran into issues when running `test_force.js --use-production` which brings the version into the app name.

Also removing . from app name

---

.circleci/config.yml
shared/utils.js
test/test_force.js

- Xcode 10.2.1
- Newer Android image
- Renamed jobs for readability
- Made version checking a little more robust

Update CI 

---

sfdx/README.md
sfdx/generate_readme.sh

README for sfdx is generated using generate_readme.sh.
Had to update that script and re-ran it.
See commits for details.

Updated sfdx README

---

shared/createHelper.js

Otherwise doesn't compile with XCode 11.

Using legacy build for React Native on iOS 

---

sfdx/package.json
shared/oclifAdapter.js

Fixing issues with sfdx plugin

---

release/setup_test_branches.js

Adding latest template in list in test branch setup script

---

shared/example.usersyncs.json
shared/syncs.schema.json

Related PR: https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2142

Adding externalIdFieldName to syncs schema for ParentInfo and ChildrenInfo

---

android/package.json
hybrid/package.json
ios/package.json
react/package.json
sfdx/package.json

We don't need to run setversions.sh in all the repos (the release script will take care of it).
But we need it in the package repo in order to run test_force.js successfully

Our current release is 9.1.1 instead of 9.2.0

---

shared/constants.js

Note: Ran test_force.js (pointing to wmathurin/SalesforceMobileSDK-CordovaPlugin) successfully.

Upgrading to cordova io 6.2.0

---

.circleci/config.yml
release/release.js
setversion.sh
shared/constants.js

Also updated "next ……steps" print out.

Generating tgz for cordova plugin during release 

---

android/package.json
hybrid/package.json
ios/package.json
react/package.json
sfdx/package.json
shared/constants.js
shared/createHelper.js

Successfully ran `test_force.js --cli=forcereact` (with `shared/constants.js` pointing to `wmathurin/SalesforceMobileSDK-Templates#rn0701`).
Also updated misc dependencies in various `package.json`.

Move to React Native 0.70.1

---

.circleci/config.yml
shared/constants.js

Increased meta space size.
Using larger instance (medium+).
Getting rid of some use sfdx jobs.

Fixing Android jobs

---

shared/createHelper.js

As a side effect, that will address: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3721

We no longer need to tweak the pod file for hybrid apps

---

release/release.js
shared/constants.js

Changing default values offered by the prompt of release.js.
NB: we don't need to change them, it just make the release just a bit easier - reduced chance of typos.

Getting ready for 12.2
